name: Upload Artifact

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1

            - name: ls
              run : ls -lah
              
            - name: artifact
              uses: actions/upload-artifact@v4
              with:
                name: my-artifact2
                path: ./

            - name: Send to Nexus
              run : curl --fail -u admin:nexusPass --upload-file https://github.com/terezA91/artifact-demo/actions/runs/8770799522/artifacts/1432919894 'https://dfb7-46-162-197-47.ngrok-free.app/repository/for-git-repo/'


