name: Upload Artifact

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1

            - name: ls
              run : ls -lah
              
            - name: Build artifact
              uses: actions/upload-artifact@v4
              with:
                name: my-artifact6
                path: ./

            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: my-artifact6
              
                

            - name: LS after download artifact
              run : ls -lah    

            - name: Send to Nexus
              run : curl --fail -u admin:nexusPass --upload-file my-artifact6.zip 'https://dfb7-46-162-197-47.ngrok-free.app/repository/for-git-repo/'


