name: Upload Artifact

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout..
              uses: actions/checkout@v4.1.1

            - name: ls
              run : ls -lah
              
            - name: Build artifact
              uses: actions/upload-artifact@v4
              with:
                path: ./

            - name: Download artifact
              uses: actions/download-artifact@v4
              
            - name: Ls after downloading artifact
              run : ls -lah    

            - name: Nexus Repo Publish
              uses: sonatype-nexus-community/nexus-repo-github-action@1.0.0
              with:
                serverUrl: https://2984-46-162-197-47.ngrok-free.app
                username: ${{ secrets.NEXUS_UNAME }}
                password: ${{ secrets.NEXUS_PSW }}
                format: raw
                repository: repo-for-git
                coordinates: directory=dev
                assets: filename=artifact
                filename: artifact

            #- name: Send to Nexus
              #run : curl --fail -u admin:nexusPass --upload-file artifact  'https://2984-46-162-197-47.ngrok-free.app/repository/repo-for-git/dev'


