name: Upload Artifact

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1

            - name: ls
              run : ls -lah
              
            - name: artifact
              uses: actions/upload-artifact@v4
              with:
                name: my-artifact2
                path: ./

            #- name: Send to Nexus
              #run :     curl --fail -u admin:nexusPass --upload-file foo.jar 'http://my-nexus-server.com:8081/repository/my-raw-repo/'


